/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Salvatore
 * Created: 24-mag-2017
 */

--DB: ammdb ; user: ammdb ; pass: ammdb ;

--creazione tabella per il tipo di post
CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);
-- creazioine tabella utenti
CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    email VARCHAR(256) UNIQUE,
    urlImmaggine VARCHAR(256),
    dataNascita  Data,
    descrizione VARCHAR(1024)
);
--creazione tabella post
CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    allegato VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id)
);
--creazione tabella delle relazioni tra utenti
CREATE TABLE amici (
   seguace INTEGER,
   FOREIGN KEY (seguace) REFERENCES utenti(utente_id),
   seguito INTEGER,
   FOREIGN KEY (seguito) REFERENCES utenti(utente_id),
   PRIMARY KEY (seguace, seguito)
);

CREATE TABLE listaUtenti(
    lista_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (lista_id) REFERENCES gruppi(gruppo_id),
    utenti_gruppo_id INTEGER,
    FOREIGN KEY (utenti_gruppo_id) REFERENCES utenti(utente_id)
);

CREATE TABLE listaPostGruppo(
    lista_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (lista_id) REFERENCES gruppi(gruppo_id),
    utente_post_id INTEGER,
    FOREIGN KEY (utente_post_id) REFERENCES utenti(utente_id)
);

CREATE TABLE gruppi(
    gruppo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creatore INTEGER,
    FOREIGN KEY (creatore) REFERENCES utenti(utente_id),
    descrizione VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES listaUtenti(lista_id),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES listaPostGruppo(lista_id),
);

--Popolamento tabella utenti
INSERT INTO utenti (utente_id, name, cognome, email, password,dataNascita, urlImmaggine,descrizione)
VALUES (default,
        'Cane',
        'mordo',
        'Canecane@gmail.com',
        '123',
        'IMG/cane.jpg',
        'bau bau');

INSERT INTO utenti (utente_id, name, cognome, email, password,dataNascita, urlImmaggine,descrizione)
VALUES (default,
        'Coniglietto',
        'carino',
        'Coniconiglietto@gmail.com',
        '123',
        'IMG/coniglietto.jpg',
        'gni gni');

INSERT INTO utenti (utente_id, name, cognome, email, password,dataNascita, urlImmaggine,descrizione)
VALUES (default,
        'Maialino',
        'puzzo',
        'maialino@gmail.com',
        '123',
        'IMG/maialino.jpg',
        'crow corw');

--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

--Popolamento tabella Post
INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        1,
        'Buongiorno Buongiorno mi chiamo francesco!!!',
        '',
        1);

INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        1,
        'Scusa Scusa Scusa, non capisco che stai dicendo',
        'IMG/cane-sordo.jpg',
        2);

INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        2,
        'che barba che noia che barba, ste erbe sono tutte uguali',
        '',
        1);

INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        1,
        'Dobbiamo stare vicini vicini <3',
        'IMG/conigli-vicini.jpg',
        2);

INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        1,
        'che palle questi umani non capiscono che a me piace rotolarmi nel fango ed essere sempre sporco!!!!',
        '',
        1);

INSERT INTO posts (post_id, author, content, allegato, type )
VALUES (default,
        1,
        'Oh mia bella maialonaaaaa, vieni qui che ti faccio cantar!',
        'IMG/scrofa.jpg',
        1);

--Popolamento tabella amici (relativa alle amicizie)
INSERT INTO amici (seguace, seguito)
VALUES (1, 2),
       (1, 3),
       (2, 1),
       (2, 3);

INSERT INTO amici (seguace, seguito)
VALUES (3, 1),
       (3, 2);
